[package]
name = "holochain"
version = "0.0.52-alpha2"
description = "holochain"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
crossbeam-channel = "=0.3.8"
holochain_persistence_api = "=0.0.18"
holochain_core = { version = "=0.0.52-alpha2", path = "../core" }
holochain_core_types = { version = "=0.0.52-alpha2", path = "../core_types" }
holochain_conductor_lib = { version = "=0.0.52-alpha2", path = "../conductor_lib" }
holochain_wasm_utils = { version = "=0.0.52-alpha2", path = "../wasm_utils" }
lib3h_sodium = "=0.0.42"
lib3h_protocol = "=0.0.42"
holochain_common = { version = "=0.0.52-alpha2", path = "../common" }
holochain_locksmith = { version = "=0.0.52-alpha2", path = "../locksmith" }
holochain_tracing = "=0.0.24"
holochain_tracing_macros = "=0.0.24"
structopt-derive = "=0.2.18"
structopt = "=0.2.18"
tiny_http = "=0.6.2"
lazy_static = "=1.4.0"
ws = "=0.8.0"
log = "=0.4.8"
newrelic = { version = "=0.2.2", optional = true }
serde_json = "=1.0.47"
shrust = "0.0.7"
im = { version = "=14.0.0", features = ["serde"] }
protobuf = "=2.14.0"

[target.'cfg(unix)'.dependencies]
signal-hook = "=0.1.10"

[features]
default = []
newrelic-on = ["newrelic"]
